apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-pvclaim
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: ""
    resources:
        requests:
            storage: 1Gi