apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
	replicas: 2
	selector:
	  matchLabels:
	    run: myapp
	template:
	  metadata:
		labels:
			run: myapp
	spec:
		containers:
		- image: nginx
		  name: myapp
		  ports:
		  - containerPort: 80
		  protocol: TCP
		nodeSelector:
		  instance=mylabel