apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    name: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
            - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/httpd/mywebsiteconf"
          name: pvclaim
          subPath:conf
        - mountPath: "/var/log/httpd-accesslog"
          name: pvclaim
          subPath: access-logs
        - mountPath: "/var/log/httpd-errorlog"
          name: pvclaim
          subPath: error-logs
      volumes:
      - name: pvclaim
        persistentVolumeClaim:
           claimName: nfs-pvclaim