# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  
  config.vm.define "master" do |master|
     master.vm.hostname="master.internal"
	 master.vm.network :private_network, ip: "192.168.1.100"
	 master.vm.provider :virtualbox do |ps|
	   ps.memory=2048
	 end
  end  
  
  config.vm.define "node1" do |node1|
     node1.vm.hostname="node1.internal"
	 node1.vm.network :private_network, ip: "192.168.1.101"
	 node1.vm.provider :virtualbox do |ps|
	   ps.memory=2048
	 end
  end 


  config.vm.define "node2" do |node2|
     node2.vm.hostname="node2.internal"
	 node2.vm.network :private_network, ip: "192.168.1.102"
	 node2.vm.provider :virtualbox do |ps|
	   ps.memory=1024
	 end
  end 
end
