# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$script = <<-SCRIPT

#Adding docker repo
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

#Installing and starting docker
yum -y install docker-ce;systemctl enable docker;systemctl start docker

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF


# kubelet requires swap off
swapoff -a

#make swap off even machine restart
sed -i '/swap/ s/^/#/' /etc/fstab

#disableing SELINUX
setenforce 0
sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config

yum install -y kubelet kubeadm kubectl nfs-utils

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

systemctl enable kubelet
systemctl start kubelet
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  
  config.vm.define "master" do |master|
     master.vm.hostname="master.internal"
	 master.vm.network :private_network, ip: "192.168.1.100"
	 master.vm.provider :virtualbox do |ps|
	   ps.memory=2048
	 end
  end  
  
  config.vm.define "node1" do |node1|
     node1.vm.hostname="node1.internal"
	 node1.vm.network :private_network, ip: "192.168.1.101"
	 node1.vm.provider :virtualbox do |ps|
	   ps.memory=2048
	 end
  end 


  config.vm.define "node2" do |node2|
     node2.vm.hostname="node2.internal"
	 node2.vm.network :private_network, ip: "192.168.1.102"
	 node2.vm.provider :virtualbox do |ps|
	   ps.memory=1024
	 end
  end 
end
