apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        # FIXME: use the right IP
        server: 10.150.18.228
        path: "/app/savio"