apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pvclaim
    labels:
    app: wordpress
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: ""
    resources:
        requests:
            storage: 10Gi
---
