apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name:  nodejsapp
        image:  saviovettoor/nodejsapp:v2
        #To fetch the image from local only(not from docker hub)
        #imagePullPolicy: Never
        ports:
        - containerPort: 2000