apiVersion: v1
kind: Service
metadata:
  name: my-nodejsapp-service
  labels:
    app: nodejsapp
spec:
  type: NodePort
  ports:
    #port where our app running in the container
  - port: 2000
    protocol: TCP
    #port which want to expose to outside
    nodePort: 30003
  selector:
    app: nodejsapp
